-- MySQL Script generated by MySQL Workbench
-- Sun Apr  8 23:39:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Kanna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Kanna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Kanna` DEFAULT CHARACTER SET utf8 ;
USE `Kanna` ;

-- -----------------------------------------------------
-- Table `Kanna`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `condicion` TINYINT(1) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Articulo` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `precioCompra` VARCHAR(45) NULL,
  `precioVenta` VARCHAR(45) NULL,
  `stock` INT NULL,
  `descripcion` VARCHAR(45) NULL,
  `estado` TINYINT(1) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idArticulo`),
  INDEX `fk_Articulo_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Articulo_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `Kanna`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Persona` (
  `idPersona` INT NOT NULL,
  `cedula` VARCHAR(45) NULL,
  `fechaNacimiento` DATETIME NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `montoTotal` FLOAT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`DetallePedido` (
  `idDetallePedido` INT NOT NULL,
  `cantidad` INT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `fk_DetallePedido_Pedido1_idx` (`Pedido_idPedido` ASC),
  INDEX `fk_DetallePedido_Articulo1_idx` (`Articulo_idArticulo` ASC),
  CONSTRAINT `fk_DetallePedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Kanna`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallePedido_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `Kanna`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `montoTotal` FLOAT NULL,
  PRIMARY KEY (`idFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Cajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Cajero` (
  `idCajero` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idCajero`),
  INDEX `fk_Cajero_Persona1_idx` (`Persona_idPersona` ASC),
  INDEX `fk_Cajero_Factura1_idx` (`Factura_idFactura` ASC),
  CONSTRAINT `fk_Cajero_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Kanna`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cajero_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `Kanna`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Almacen` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `totalComprado` INT NULL,
  `totalVendido` INT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  PRIMARY KEY (`idAlmacen`),
  INDEX `fk_Almacen_Articulo_idx` (`Articulo_idArticulo` ASC),
  CONSTRAINT `fk_Almacen_Articulo`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `Kanna`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`OrdenCompra` (
  `idOrdenCompra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `montoTotal` FLOAT NULL,
  PRIMARY KEY (`idOrdenCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`DetalleOrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`DetalleOrdenCompra` (
  `idDetalleOrdenCompra` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `OrdenCompra_idOrdenCompra` INT NOT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  PRIMARY KEY (`idDetalleOrdenCompra`),
  INDEX `fk_DetalleOrdenCompra_OrdenCompra1_idx` (`OrdenCompra_idOrdenCompra` ASC),
  INDEX `fk_DetalleOrdenCompra_Articulo1_idx` (`Articulo_idArticulo` ASC),
  CONSTRAINT `fk_DetalleOrdenCompra_OrdenCompra1`
    FOREIGN KEY (`OrdenCompra_idOrdenCompra`)
    REFERENCES `Kanna`.`OrdenCompra` (`idOrdenCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleOrdenCompra_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `Kanna`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Devolucion` (
  `idDevolucion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `montoTotal` FLOAT NULL,
  PRIMARY KEY (`idDevolucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`DetalleDevolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`DetalleDevolucion` (
  `idDetalleDevolucion` INT NOT NULL AUTO_INCREMENT,
  `DetalleDevolucion` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `Devolucion_idDevolucion` INT NOT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  PRIMARY KEY (`idDetalleDevolucion`),
  INDEX `fk_DetalleDevolucion_Devolucion1_idx` (`Devolucion_idDevolucion` ASC),
  INDEX `fk_DetalleDevolucion_Articulo1_idx` (`Articulo_idArticulo` ASC),
  CONSTRAINT `fk_DetalleDevolucion_Devolucion1`
    FOREIGN KEY (`Devolucion_idDevolucion`)
    REFERENCES `Kanna`.`Devolucion` (`idDevolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleDevolucion_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `Kanna`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`FormaDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`FormaDePago` (
  `idFormaDePago` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormaDePago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Administrador_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Kanna`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`DetalleFactura` (
  `idDetalleFactura` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  `Factura_idFactura` INT NOT NULL,
  PRIMARY KEY (`idDetalleFactura`),
  INDEX `fk_DetalleFactura_Articulo1_idx` (`Articulo_idArticulo` ASC),
  INDEX `fk_DetalleFactura_Factura1_idx` (`Factura_idFactura` ASC),
  CONSTRAINT `fk_DetalleFactura_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `Kanna`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleFactura_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `Kanna`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Kanna`.`Suplidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Kanna`.`Suplidor` (
  `idSuplidor` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `FormaDePago_idFormaDePago` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idSuplidor`),
  INDEX `fk_Suplidor_Pedido1_idx` (`Pedido_idPedido` ASC),
  INDEX `fk_Suplidor_FormaDePago1_idx` (`FormaDePago_idFormaDePago` ASC),
  INDEX `fk_Suplidor_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Suplidor_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Kanna`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suplidor_FormaDePago1`
    FOREIGN KEY (`FormaDePago_idFormaDePago`)
    REFERENCES `Kanna`.`FormaDePago` (`idFormaDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suplidor_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Kanna`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
