-- MySQL Script generated by MySQL Workbench
-- Sat Jun 30 12:39:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShuxhyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShuxhyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShuxhyDB` DEFAULT CHARACTER SET utf8 ;
USE `ShuxhyDB` ;

-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `UsuarioIG` VARCHAR(25) NOT NULL,
  `Comentario` VARCHAR(200) NOT NULL DEFAULT 'NA',
  `Telefono` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL DEFAULT 'NA',
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCliente`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT 'NA',
  `Peso` FLOAT NULL DEFAULT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  `CostoProduccion` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL DEFAULT 0,
  `Forma` VARCHAR(20) NULL DEFAULT NULL,
  `Topping` VARCHAR(20) NULL DEFAULT NULL,
  `Relleno` VARCHAR(20) NULL DEFAULT NULL,
  `Sabor` VARCHAR(20) NULL DEFAULT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  `Imagen` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Combo` (
  `IdCombo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(10) NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  `Descuento` FLOAT NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  `Imagen` VARCHAR(50) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCombo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleCombo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleCombo` (
  `IdDetalleCombo` INT NOT NULL AUTO_INCREMENT,
  `IdCombo` INT NOT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `IdProducto` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  PRIMARY KEY (`IdDetalleCombo`),
  INDEX `fk_Idcombo_DescripcionCombo_idx` (`IdCombo` ASC),
  INDEX `fk_idproducto_detallecombo_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_Idcombo_DetalleCombo`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`IdCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idproducto_detallecombo`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Pedido` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NULL DEFAULT NULL,
  `EntregaPedido` VARCHAR(45) NULL DEFAULT NULL,
  `DireccionEntrega` VARCHAR(45) NULL DEFAULT NULL,
  `FechaRealizado` DATETIME NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  `Comentario` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPedido`),
  INDEX `fk_IdCliente_Pedido_idx` (`IdCliente` ASC),
  CONSTRAINT `fk_IdCliente_Pedido`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `ShuxhyDB`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetallePedido` (
  `IdDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `IdCombo` INT NULL DEFAULT NULL,
  `IdProducto` INT NULL DEFAULT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `Subtotal` FLOAT NOT NULL,
  `PrecioPorUnidad` FLOAT NOT NULL,
  `Comentario` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetallePedido`),
  INDEX `fk_IdPedido_Descripcion_idx` (`IdPedido` ASC),
  INDEX `fk_IdCombo_Pedido_idx` (`IdCombo` ASC),
  INDEX `fk_IdProducto_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_IdPedido_Descripcion`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdCombo_Pedido`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`IdCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdProducto`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Factura` (
  `IdFactura` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `TotalFacturado` FLOAT NOT NULL,
  `FormaPago` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdFactura`),
  UNIQUE INDEX `IdPedido_UNIQUE` (`IdPedido` ASC),
  CONSTRAINT `Fk_IdPedido_Factura`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Receta` (
  `IdReceta` INT NOT NULL,
  `NombreReceta` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Equipo` VARCHAR(45) NULL DEFAULT NULL,
  `SubTotal` FLOAT NULL DEFAULT NULL,
  `CostoIndirecto` FLOAT NULL DEFAULT NULL,
  `CostoManoDeObra` FLOAT NULL DEFAULT NULL,
  `CostoDeReposicion` FLOAT NULL DEFAULT NULL,
  `TiempoPreparacion` VARCHAR(45) NULL DEFAULT NULL,
  `Porcion` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdReceta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Produccion` (
  `IdProduccion` INT NOT NULL AUTO_INCREMENT,
  `IdProducto` INT NOT NULL,
  `IdReceta` INT NOT NULL,
  PRIMARY KEY (`IdProduccion`),
  INDEX `fk_idproducto_idx` (`IdProducto` ASC),
  INDEX `fk_idreceta_idx` (`IdReceta` ASC),
  CONSTRAINT `fk_idproducto_produccion`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idreceta_produccion`
    FOREIGN KEY (`IdReceta`)
    REFERENCES `ShuxhyDB`.`Receta` (`IdReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Material` (
  `IdMaterial` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `Unidad` VARCHAR(45) NULL DEFAULT NULL,
  `Peso` FLOAT NULL DEFAULT NULL,
  `Costo` FLOAT NOT NULL,
  `Imagen` VARCHAR(50) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Inventario` (
  `IdInventario` INT NOT NULL AUTO_INCREMENT,
  `IdProducto` INT NULL DEFAULT NULL,
  `IdMaterial` INT NULL DEFAULT NULL,
  `Cantidad` FLOAT NOT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  `PesoPorUnidad` FLOAT NOT NULL DEFAULT 0,
  `PesoTotal` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`IdInventario`),
  INDEX `fk_producto_idx` (`IdProducto` ASC),
  INDEX `fk_material_inventario_idx` (`IdMaterial` ASC),
  CONSTRAINT `fk_producto`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_inventario`
    FOREIGN KEY (`IdMaterial`)
    REFERENCES `ShuxhyDB`.`Material` (`IdMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleReceta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleReceta` (
  `IdDetalleReceta` INT NOT NULL AUTO_INCREMENT,
  `IdReceta` INT NULL DEFAULT NULL,
  `IdMaterial` INT NOT NULL,
  `Cantidad` FLOAT NOT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  `CostoPorMaterial` FLOAT NOT NULL,
  PRIMARY KEY (`IdDetalleReceta`),
  INDEX `fk_material_detallereceta_idx` (`IdMaterial` ASC),
  INDEX `fk_receta_detallereceta_idx` (`IdReceta` ASC),
  CONSTRAINT `fk_material_detallereceta`
    FOREIGN KEY (`IdMaterial`)
    REFERENCES `ShuxhyDB`.`Material` (`IdMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_detallereceta`
    FOREIGN KEY (`IdReceta`)
    REFERENCES `ShuxhyDB`.`Receta` (`IdReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ShuxhyDB` ;

-- -----------------------------------------------------
-- procedure Preciounidaddetallecombo&pedido
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `Preciounidaddetallecombo&pedido` ()
BEGIN
UPDATE DetallePedido
Set PrecioPorUnidad= (Select Precio, Total
       from Producto, Combo
	Where ((DetallePedido.IdProducto = Producto.IdProducto) or (DetallePedido.IdCombo = Combo.IdCombo))); 
    
UPDATE DetalleCombo
Set Precio= (Select Precio
       from Producto 
	Where Producto.IdProducto = DetalleCombo.IdProducto); 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DetallePedidoSubtotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `DetallePedidoSubtotal` ()
BEGIN
UPDATE DetallePedido
SET Subtotal = PrecioPorUnidad*Cantidad;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ComboSubtotal&Total
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `ComboSubtotal&Total` ()
BEGIN
UPDATE Combo
SET Subtotal = ( select Sum(Subtotal)
					from DetalleCombo
				   where DetalleCombo.IdCombo=Combo.IdCombo
				 );
UPDATE Combo
SET Total = Descuento*Subtotal;
				
                 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DetalleComboSubtotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `DetalleComboSubtotal` ()
BEGIN
Update DetalleCombo
SET Subtotal = Precio*Cantidad;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure FacturalSubtotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `FacturalSubtotal` ()
BEGIN
UPDATE Factura
SET TotalFactura = ( select Sum(Subtotal)
					from DetallePedido
				    where (DetallePedido.IdPedido=Pedido.IdPedido 
                    and Factura.IdPedido=Pedido.IdPedido)
				 );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure InventarioPesoTotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `InventarioPesoTotal` ()
BEGIN

UPDATE Inventario
SET PesoTotal = PesoPorUnidad*Cantidad;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure InventarioPesoPorUnidad
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `InventarioPesoPorUnidad` ()
BEGIN
UPDATE Inventario
SET PesoPorUnidad = (select(Peso,Peso) from Material,Producto 
					where 
                    ((Inventario.IdMaterial=Material.IdMaterial) 
                    or 
                    (Inventario.IdProducto=Producto.IdProducto)))


;

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
