-- MySQL Script generated by MySQL Workbench
-- Fri Jul  6 22:30:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ShuxhyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShuxhyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShuxhyDB` DEFAULT CHARACTER SET utf8 ;
USE `ShuxhyDB` ;

-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `UsuarioIG` VARCHAR(25) NOT NULL,
  `Comentario` VARCHAR(200) NOT NULL DEFAULT 'NA',
  `Telefono` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL DEFAULT 'NA',
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCliente`),
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Unidad` (
  `IdUnidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`IdUnidad`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Abreviatura_UNIQUE` (`Abreviatura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Relleno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Relleno` (
  `IdRelleno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`IdRelleno`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Abreviatura_UNIQUE` (`Abreviatura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Sabor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Sabor` (
  `IdSabor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`IdSabor`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Abreviatura_UNIQUE` (`Abreviatura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Forma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Forma` (
  `IdForma` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`IdForma`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Abreviatura_UNIQUE` (`Abreviatura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Topping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Topping` (
  `IdTopping` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`IdTopping`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC),
  UNIQUE INDEX `Abreviatura_UNIQUE` (`Abreviatura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Producto` (
  `IdProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT 'NA',
  `IdUnidad` INT NOT NULL,
  `CostoProduccion` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL DEFAULT 0,
  `IdForma` INT NOT NULL,
  `IdTopping` INT NOT NULL,
  `IdRelleno` INT NOT NULL,
  `IdSabor` INT NOT NULL,
  `Condicion` TINYINT NULL DEFAULT NULL,
  `Imagen` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProducto`),
  INDEX `fk_IdUnidad_Producto_idx` (`IdUnidad` ASC),
  INDEX `fk_IdForma_Producto_idx` (`IdForma` ASC),
  INDEX `fk_IdTopping_Producto_idx` (`IdTopping` ASC),
  INDEX `fk_IdRelleno_Producto_idx` (`IdRelleno` ASC),
  INDEX `fk_IdSabor_Producto_idx` (`IdSabor` ASC),
  CONSTRAINT `fk_IdUnidad_Producto`
    FOREIGN KEY (`IdUnidad`)
    REFERENCES `ShuxhyDB`.`Unidad` (`IdUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdForma_Producto`
    FOREIGN KEY (`IdForma`)
    REFERENCES `ShuxhyDB`.`Forma` (`IdForma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdTopping_Producto`
    FOREIGN KEY (`IdTopping`)
    REFERENCES `ShuxhyDB`.`Topping` (`IdTopping`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdRelleno_Producto`
    FOREIGN KEY (`IdRelleno`)
    REFERENCES `ShuxhyDB`.`Relleno` (`IdRelleno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdSabor_Producto`
    FOREIGN KEY (`IdSabor`)
    REFERENCES `ShuxhyDB`.`Sabor` (`IdSabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Combo` (
  `IdCombo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  `Descuento` FLOAT NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  `Imagen` VARCHAR(50) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCombo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleCombo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleCombo` (
  `IdDetalleCombo` INT NOT NULL AUTO_INCREMENT,
  `IdCombo` INT NOT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `IdProducto` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`IdDetalleCombo`),
  INDEX `fk_Idcombo_DescripcionCombo_idx` (`IdCombo` ASC),
  INDEX `fk_idproducto_detallecombo_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_Idcombo_DetalleCombo`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`IdCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idproducto_detallecombo`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Pedido` (
  `IdPedido` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NULL DEFAULT NULL,
  `Estadus` VARCHAR(45) NULL DEFAULT NULL,
  `DireccionEntrega` VARCHAR(45) NULL DEFAULT NULL,
  `FechaRealizado` DATETIME NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  `Total` FLOAT NOT NULL,
  `Comentario` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPedido`),
  INDEX `fk_IdCliente_Pedido_idx` (`IdCliente` ASC),
  CONSTRAINT `fk_IdCliente_Pedido`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `ShuxhyDB`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetallePedido` (
  `IdDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `IdCombo` INT NULL DEFAULT NULL,
  `IdProducto` INT NULL DEFAULT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `Subtotal` FLOAT NOT NULL,
  `PrecioProducto` FLOAT NOT NULL,
  `PrecioCombo` FLOAT NOT NULL,
  `Comentario` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetallePedido`),
  INDEX `fk_IdPedido_Descripcion_idx` (`IdPedido` ASC),
  INDEX `fk_IdCombo_Pedido_idx` (`IdCombo` ASC),
  INDEX `fk_IdProducto_idx` (`IdProducto` ASC),
  CONSTRAINT `fk_IdPedido_Descripcion`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdCombo_Pedido`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`IdCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdProducto`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Factura` (
  `IdFactura` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NULL DEFAULT NULL,
  `IdProducto` INT NULL DEFAULT NULL,
  `IdCombo` INT NULL DEFAULT NULL,
  `Fecha` DATETIME NOT NULL,
  `TotalFacturado` FLOAT NOT NULL,
  `FormaPago` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdFactura`),
  UNIQUE INDEX `IdPedido_UNIQUE` (`IdPedido` ASC),
  INDEX `Fk_IdProducto_Factura` (`IdProducto` ASC),
  INDEX `Fk_IdCombo_Factura` (`IdCombo` ASC),
  CONSTRAINT `Fk_IdPedido_Factura`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_IdProducto_Factura`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_IdCombo_Factura`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`IdCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleFactura` (
  `IdDetalleFactura` INT NOT NULL AUTO_INCREMENT,
  `IdFactura` INT NULL DEFAULT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `Subtotal` FLOAT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Comentario` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetalleFactura`),
  INDEX `fk_IdFactura_Descripcion_idx` (`IdFactura` ASC),
  CONSTRAINT `fk_IdFactura_Descripcion`
    FOREIGN KEY (`IdFactura`)
    REFERENCES `ShuxhyDB`.`Factura` (`IdFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Material` (
  `IdMaterial` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `IdUnidad` INT NOT NULL,
  `Costo` FLOAT NOT NULL,
  `Imagen` VARCHAR(50) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMaterial`),
  INDEX `fk_IdUnidad_material_idx` (`IdUnidad` ASC),
  CONSTRAINT `fk_IdUnidad_material`
    FOREIGN KEY (`IdUnidad`)
    REFERENCES `ShuxhyDB`.`Unidad` (`IdUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Receta` (
  `IdReceta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `Equipo` VARCHAR(100) NULL DEFAULT NULL,
  `SubTotal` FLOAT NULL DEFAULT NULL,
  `CostoIndirecto` FLOAT NULL DEFAULT NULL,
  `CostoManoDeObra` FLOAT NULL DEFAULT NULL,
  `CostoDeReposicion` FLOAT NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  `TiempoPreparacion` VARCHAR(45) NULL DEFAULT NULL,
  `Porcion` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IdReceta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleReceta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleReceta` (
  `IdDetalleReceta` INT NOT NULL AUTO_INCREMENT,
  `IdReceta` INT NULL DEFAULT NULL,
  `IdMaterial` INT NOT NULL,
  `Cantidad` FLOAT NOT NULL,
  `IdUnidad` INT NOT NULL,
  `CostoMaterial` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetalleReceta`),
  INDEX `fk_material_detallereceta_idx` (`IdMaterial` ASC),
  INDEX `fk_receta_detallereceta_idx` (`IdReceta` ASC),
  INDEX `fk_unidad_detallereceta_idx` (`IdUnidad` ASC),
  CONSTRAINT `fk_material_detallereceta`
    FOREIGN KEY (`IdMaterial`)
    REFERENCES `ShuxhyDB`.`Material` (`IdMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receta_detallereceta`
    FOREIGN KEY (`IdReceta`)
    REFERENCES `ShuxhyDB`.`Receta` (`IdReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unidad_detallereceta`
    FOREIGN KEY (`IdUnidad`)
    REFERENCES `ShuxhyDB`.`Unidad` (`IdUnidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Produccion` (
  `IdProduccion` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `IdPedido` INT NULL DEFAULT NULL,
  `Estatus` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProduccion`),
  INDEX `fk_pedido_produccion_idx` (`IdPedido` ASC),
  CONSTRAINT `fk_pedido_produccion`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`IdPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`InventarioProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`InventarioProd` (
  `IdInventarioProd` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Cantidad` FLOAT NOT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdInventarioProd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`ProdInventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`ProdInventario` (
  `IdProdInventario` INT NOT NULL AUTO_INCREMENT,
  `IdProducto` INT NULL DEFAULT NULL,
  `IdInventarioProd` INT NULL DEFAULT NULL,
  INDEX `fk_Producto_prodInventario_idx` (`IdProducto` ASC),
  INDEX `fk_InventarioProd_ProdInventario` (`IdInventarioProd` ASC),
  PRIMARY KEY (`IdProdInventario`),
  CONSTRAINT `fk_Producto_ProdInven`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InventarioProd_ProdInventario`
    FOREIGN KEY (`IdInventarioProd`)
    REFERENCES `ShuxhyDB`.`InventarioProd` (`IdInventarioProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`InventarioMat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`InventarioMat` (
  `IdInventarioMat` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Cantidad` FLOAT NOT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdInventarioMat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`MatInventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`MatInventario` (
  `IdMatInventario` INT NOT NULL AUTO_INCREMENT,
  `IdMaterial` INT NULL DEFAULT NULL,
  `IdInventarioMat` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdMatInventario`),
  INDEX `fk_Inventariomat_matinventario_idx` (`IdInventarioMat` ASC),
  INDEX `fk_Material_MatInventario_idx` (`IdMaterial` ASC),
  CONSTRAINT `fk_Material_MatInventario`
    FOREIGN KEY (`IdMaterial`)
    REFERENCES `ShuxhyDB`.`Material` (`IdMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventariomat_matinventario`
    FOREIGN KEY (`IdInventarioMat`)
    REFERENCES `ShuxhyDB`.`InventarioMat` (`IdInventarioMat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleProduccion` (
  `IdDetalleProduccion` INT NOT NULL AUTO_INCREMENT,
  `IdProduccion` INT NULL DEFAULT NULL,
  `IdReceta` INT NULL DEFAULT NULL,
  `CantidadProducir` INT NULL DEFAULT NULL,
  `CantidadProducida` INT NULL DEFAULT NULL,
  `CantidadFaltante` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetalleProduccion`),
  INDEX `fk_receta_DetalleProduccion_idx` (`IdReceta` ASC),
  INDEX `fk_produccion_Detalleproduccion_idx` (`IdProduccion` ASC),
  CONSTRAINT `fk_receta_DetalleProduccion`
    FOREIGN KEY (`IdReceta`)
    REFERENCES `ShuxhyDB`.`Receta` (`IdReceta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produccion_Detalleproduccion`
    FOREIGN KEY (`IdProduccion`)
    REFERENCES `ShuxhyDB`.`Produccion` (`IdProduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`MatProduccionUtilizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`MatProduccionUtilizado` (
  `IdMatProduccionUtilizado` INT NOT NULL AUTO_INCREMENT,
  `IdDetalleProduccion` INT NULL DEFAULT NULL,
  `IdMaterial` INT NULL DEFAULT NULL,
  `Cantidad` FLOAT NULL DEFAULT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMatProduccionUtilizado`),
  INDEX `fk_DetalleProduccion_idx` (`IdDetalleProduccion` ASC),
  INDEX `fk_unidad_idx` (`Unidad` ASC),
  INDEX `fk_material_idx` (`IdMaterial` ASC),
  CONSTRAINT `fk_DetalleProduccion`
    FOREIGN KEY (`IdDetalleProduccion`)
    REFERENCES `ShuxhyDB`.`DetalleProduccion` (`IdDetalleProduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material`
    FOREIGN KEY (`IdMaterial`)
    REFERENCES `ShuxhyDB`.`Material` (`IdMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`MovInventarioProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`MovInventarioProd` (
  `IdMovInventarioProducto` INT NOT NULL AUTO_INCREMENT,
  `IdInventarioProd` INT NULL DEFAULT NULL,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `TipoMov` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMovInventarioProducto`),
  INDEX `fk_InventarioProd_idx` (`IdInventarioProd` ASC),
  CONSTRAINT `fk_InventarioProd`
    FOREIGN KEY (`IdInventarioProd`)
    REFERENCES `ShuxhyDB`.`InventarioProd` (`IdInventarioProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleMovInventarioProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleMovInventarioProd` (
  `IdDetalleMovInventario` INT NOT NULL AUTO_INCREMENT,
  `IdMovInventarioProd` INT NULL DEFAULT NULL,
  `IdProducto` INT NULL DEFAULT NULL,
  `Cantidad` FLOAT NULL DEFAULT NULL,
  `Unidad` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`IdDetalleMovInventario`),
  INDEX `fk_unidad_DetalleMovInv_idx` (`Unidad` ASC),
  INDEX `fk_producto_DetalleMov_idx` (`IdProducto` ASC),
  INDEX `fk_movInventarioproducto_idx` (`IdMovInventarioProd` ASC),
  CONSTRAINT `fk_producto_DetalleMov`
    FOREIGN KEY (`IdProducto`)
    REFERENCES `ShuxhyDB`.`Producto` (`IdProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movinvprod_detalle`
    FOREIGN KEY (`IdMovInventarioProd`)
    REFERENCES `ShuxhyDB`.`MovInventarioProd` (`IdMovInventarioProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`MovInventarioMat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`MovInventarioMat` (
  `IdMovInventarioMat` INT NOT NULL AUTO_INCREMENT,
  `IdInventarioMat` INT NULL DEFAULT NULL,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `TipoMovimiento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdMovInventarioMat`),
  INDEX `fk_InventarioMat_MovInv_idx` (`IdInventarioMat` ASC),
  CONSTRAINT `fk_InventarioMat_MovInv`
    FOREIGN KEY (`IdInventarioMat`)
    REFERENCES `ShuxhyDB`.`InventarioMat` (`IdInventarioMat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `ShuxhyDB` ;

-- -----------------------------------------------------
-- procedure Preciounidaddetallecombo&pedido
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `Preciounidaddetallecombo&pedido` ()
BEGIN
UPDATE DetallePedido
Set PrecioPorUnidad= (Select Precio, Total
       from Producto, Combo
	Where ((DetallePedido.IdProducto = Producto.IdProducto) or (DetallePedido.IdCombo = Combo.IdCombo))); 
    
UPDATE DetalleCombo
Set Precio= (Select Precio
       from Producto 
	Where Producto.IdProducto = DetalleCombo.IdProducto); 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DetallePedidoSubtotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `DetallePedidoSubtotal` ()
BEGIN
UPDATE DetallePedido
SET Subtotal = PrecioPorUnidad*Cantidad;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ComboSubtotal&Total
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `ComboSubtotal&Total` ()
BEGIN
UPDATE Combo
SET Subtotal = ( select Sum(Subtotal)
					from DetalleCombo
				   where DetalleCombo.IdCombo=Combo.IdCombo
				 );
UPDATE Combo
SET Total = Descuento*Subtotal;
				
                 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DetalleComboSubtotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `DetalleComboSubtotal` ()
BEGIN
Update DetalleCombo
SET Subtotal = Precio*Cantidad;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure FacturalSubtotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `FacturalSubtotal` ()
BEGIN
UPDATE Factura
SET TotalFactura = ( select Sum(Subtotal)
					from DetallePedido
				    where (DetallePedido.IdPedido=Pedido.IdPedido 
                    and Factura.IdPedido=Pedido.IdPedido)
				 );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure InventarioPesoTotal
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `InventarioPesoTotal` ()
BEGIN

UPDATE Inventario
SET PesoTotal = PesoPorUnidad*Cantidad;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure InventarioPesoPorUnidad
-- -----------------------------------------------------

DELIMITER $$
USE `ShuxhyDB`$$
CREATE PROCEDURE `InventarioPesoPorUnidad` ()
BEGIN
UPDATE Inventario
SET PesoPorUnidad = (select(Peso,Peso) from Material,Producto 
					where 
                    ((Inventario.IdMaterial=Material.IdMaterial) 
                    or 
                    (Inventario.IdProducto=Producto.IdProducto)))


;

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
