-- MySQL Script generated by MySQL Workbench
-- 05/27/18 07:30:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShuxhyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShuxhyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShuxhyDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ShuxhyDB` ;

-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `Usuario` VARCHAR(25) NOT NULL,
  `Descripcion` VARCHAR(15) NOT NULL DEFAULT 'NA',
  `Telefono` VARCHAR(20) NOT NULL,
  `Dirreccion` VARCHAR(45) NOT NULL DEFAULT 'NA',
  `FechaIngreso` DATETIME NOT NULL,
  PRIMARY KEY (`IdCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT 'NA',
  `Cantidad` INT NOT NULL DEFAULT 0,
  `Precioporunidad` FLOAT NOT NULL DEFAULT 0,
  `Unidad_entero` INT NOT NULL DEFAULT 0,
  `Unidad_medida` VARCHAR(20) NOT NULL DEFAULT 'NA',
  `Unidad_Onzas` VARCHAR(20) NOT NULL DEFAULT 'NA',
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Empleado` (
  `IdEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `FechaEntrada` DATETIME NOT NULL,
  `FechaNacimiento` DATETIME NOT NULL,
  `Dirreccion` VARCHAR(45) NOT NULL,
  `SalarioActual` FLOAT NOT NULL,
  `Posicion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `TipoUsuario` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `IdEmpleado` INT NULL,
  `Usuario` VARCHAR(15) NOT NULL,
  `IdTiposuario` INT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Salario` FLOAT NOT NULL,
  `Usuariocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`, `Usuariocol`),
  INDEX `fk_idEmpleado_Usuario_idx` (`IdEmpleado` ASC),
  INDEX `fk_idTipousuario_usuario_idx` (`IdTiposuario` ASC),
  CONSTRAINT `fk_idEmpleado_Usuario`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `ShuxhyDB`.`Empleado` (`IdEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idTipousuario_usuario`
    FOREIGN KEY (`IdTiposuario`)
    REFERENCES `ShuxhyDB`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`FormaPostre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`FormaPostre` (
  `idFormaPostre` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idFormaPostre`, `Nombre`, `Descripcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`SaborPostre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`SaborPostre` (
  `idSaborPostre` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idSaborPostre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`RellenoPostre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`RellenoPostre` (
  `idRellenoPostre` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idRellenoPostre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`ToppingPostre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`ToppingPostre` (
  `idToppingPostre` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idToppingPostre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `Producto` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  `IdForma` INT NULL,
  `IdRelleno` INT NULL,
  `IdTopping` INT NULL,
  `IdSabor` INT NULL,
  `Precio` FLOAT NULL,
  PRIMARY KEY (`idMenu`, `Producto`),
  INDEX `fk_Idforma_Menu_idx` (`IdForma` ASC),
  INDEX `fk_Idsabor_menu_idx` (`IdSabor` ASC),
  INDEX `fk_IdRelleno_Menu_idx` (`IdRelleno` ASC),
  INDEX `Fk_IdTopping_Menu_idx` (`IdTopping` ASC),
  CONSTRAINT `fk_Idforma_Menu`
    FOREIGN KEY (`IdForma`)
    REFERENCES `ShuxhyDB`.`FormaPostre` (`idFormaPostre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idsabor_menu`
    FOREIGN KEY (`IdSabor`)
    REFERENCES `ShuxhyDB`.`SaborPostre` (`idSaborPostre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdRelleno_Menu`
    FOREIGN KEY (`IdRelleno`)
    REFERENCES `ShuxhyDB`.`RellenoPostre` (`idRellenoPostre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_IdTopping_Menu`
    FOREIGN KEY (`IdTopping`)
    REFERENCES `ShuxhyDB`.`ToppingPostre` (`idToppingPostre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Combo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Combo` (
  `idCombo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(10) NOT NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idCombo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DescripcionCombo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DescripcionCombo` (
  `idDescripcionCombo` INT NOT NULL AUTO_INCREMENT,
  `IdCombo` INT NOT NULL,
  `Nombre` VARCHAR(10) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idDescripcionCombo`),
  INDEX `fk_Idcombo_DescripcionCombo_idx` (`IdCombo` ASC),
  CONSTRAINT `fk_Idcombo_DescripcionCombo`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`idCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`TipoPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`TipoPedido` (
  `idTipoPedido` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(15) NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NULL,
  `IdTipoPedido` INT NULL,
  `DirreccionEntrega` VARCHAR(45) NULL,
  `FechaRealizado` DATETIME NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_IdCliente_Pedido_idx` (`IdCliente` ASC),
  INDEX `fk_IdTipoPedido_Pedido_idx` (`IdTipoPedido` ASC),
  CONSTRAINT `fk_IdCliente_Pedido`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `ShuxhyDB`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdTipoPedido_Pedido`
    FOREIGN KEY (`IdTipoPedido`)
    REFERENCES `ShuxhyDB`.`TipoPedido` (`idTipoPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DescripcionPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DescripcionPedido` (
  `idDescripcionPedido` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `IdMenu` INT NOT NULL,
  `IdCombo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idDescripcionPedido`),
  INDEX `fk_IdPedido_Descripcion_idx` (`IdPedido` ASC),
  INDEX `fk_IdCombo_Pedido_idx` (`IdCombo` ASC),
  INDEX `fk_IdMen_Pedido_idx` (`IdMenu` ASC),
  CONSTRAINT `fk_IdPedido_Descripcion`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdCombo_Pedido`
    FOREIGN KEY (`IdCombo`)
    REFERENCES `ShuxhyDB`.`Combo` (`idCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IdMen_Pedido`
    FOREIGN KEY (`IdMenu`)
    REFERENCES `ShuxhyDB`.`Menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `IdPedido` INT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `TotalFacturado` FLOAT NOT NULL,
  PRIMARY KEY (`idFactura`),
  UNIQUE INDEX `IdPedido_UNIQUE` (`IdPedido` ASC),
  CONSTRAINT `Fk_IdPedido_Factura`
    FOREIGN KEY (`IdPedido`)
    REFERENCES `ShuxhyDB`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShuxhyDB`.`DetalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShuxhyDB`.`DetalleFactura` (
  `idDetalleFactura` INT NOT NULL AUTO_INCREMENT,
  `IdFactura` INT NOT NULL,
  `IdDescripcionPedido` INT NOT NULL,
  `Precioporunidad` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  PRIMARY KEY (`idDetalleFactura`),
  UNIQUE INDEX `IdDescripcionPedido_UNIQUE` (`IdDescripcionPedido` ASC),
  INDEX `Fk_IdFactura_DetalleFactura_idx` (`IdFactura` ASC),
  CONSTRAINT `Fk_IdFactura_DetalleFactura`
    FOREIGN KEY (`IdFactura`)
    REFERENCES `ShuxhyDB`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_IdDescripcionPedido_DetalleFactura`
    FOREIGN KEY (`IdDescripcionPedido`)
    REFERENCES `ShuxhyDB`.`DescripcionPedido` (`idDescripcionPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
